export default {
    BUTTON_ACCEPT: 'Accept',
    BUTTON_CANCEL: 'Cancel',
    BUTTON_SAVE: 'Save',
    BUTTON_RESERVE: 'Reserve',
    BUTTON_BUY: 'Buy',
    BUTTON_LOGIN: 'Login',
    BUTTON_LOGOUT: 'Logout',
    BUTTON_REGISTER: 'Register',
    BUTTON_PASSWORD_FORGOT: 'Restore password',
    BUTTON_PASSWORD_CHANGE: 'Change password',
    BUTTON_PROFILE: 'User profile',
    BUTTON_BACK: 'Back',
    VALIDATION_EMAIL: 'is not valid. Verify your username and the domain address.',
    VALIDATION_PASSWORD: 'too short. Use 6 or more characters.',
    VALIDATION_EQUAL_PASSWORDS: 'and the password don\'t coincide.',
    VALIDATION_FULL_NAME: 'should not be empty.',
    THE_FIELD: 'The field ',
    LOGIN_SUCCESS: 'You\'ve logged in successfully',
    REGISTER_SUCCESS: 'You\'ve registered successfully',
    SAVE_ME_SUCCESS: 'User information saved correctly',
    PASSWORD_FORGOT_SUCCESS: 'We\'ve sent you a link to restore your password',
    PASSWORD_CHANGE_SUCCESS: 'The password has been changed correctly',
    LABEL_EMAIL: 'E-Mail',
    LABEL_PASSWORD: 'Password',
    LABEL_PASSWORD_CONFIRM: 'Confirm password',
    LABEL_FULL_NAME: 'Full name',
    LABEL_FIRST_NAME: 'Name(s)',
    LABEL_LAST_NAME: 'Last name(s)',
    LABEL_BIRTH_DATE: 'Brth date',
    LABEL_PICTURE: 'Profile Image',
    LABEL_ADDRESS: 'Address',
    LABEL_INTERNAL_NUMBER: 'Interior',
    LABEL_EXTERNAL_NUMBER: 'Exterior',
    LABEL_MUNICIPALITY: 'Municipality',
    LABEL_CITY: 'City',
    LABEL_COUNTRY: 'Country',
    LABEL_STATE: 'State',
    LABEL_PHONE: 'Phone',
    LABEL_CEL_PHONE: 'Celphone',
    LABEL_GENDER: 'Gender',
    LABEL_POSTAL_CODE: 'ZIP code',
    LABEL_PROFILE_INFO: 'User data',
    LABEL_CONTACT: 'Contact',
    TO_VALIDATION: {
        email: 'email',
        password: 'password',
        passwordConfirmation: 'confirm password',
        fullName: 'full name',
        first_name: 'name',
    },
    EXPIRE_IN: "Expires in ",
    DAYS: "days",
    MEMBERSHIPS: "Memberships",
    COMBOS: "Combos",
    STAFF_LIST: "Staff",
    SERVICE_LIST: "Services",
    ALL: 'All',
    LOCATION: 'Location',
    SERVICE: 'Service',
    ROOM: 'Room',
    NEXT_WEEK: 'Next week',
    PREVIOUS_WEEK: 'Previous week',
    CALENDAR: 'Calendar',
    NOT_ACCOUNT_QUESTION: "Don\'t have an account yet?",
    ACCOUNT_QUESTION: "Already have an account?",
    FORGOT_PASSWORD_QUESTION: "Forgot your password?",
    TIME_OF_DAY: 'Time of day',
    MORNING: 'Morning',
    AFTERNOON: 'Afternoon',
    CHANGEPASSWORD: 'Change password',
    NEWPASSWORD: 'New password',
    PASSWORDCONFIRM: 'Confirm password',
    EXPIRATION: 'Expires:',
    CREDITS: 'Available credits',
    STORE_CREDIT_AVAILABLE: 'Available store credit',
    CREATE: 'Created since:',
    CLASS: 'My classes',
    PROFILE: 'My profile',
    PAYMENTMETHODS: 'Payment types',
    CREDIT: 'Credit: ',
    MEMBERSHIP: 'Membership: ',
    BEGINS: 'Starts: ',
    FUTURESCLASSES: 'Upcoming Classes',
    PASTCLASSES: 'Past Classes',
    PURCHASES: 'Purchases',
    POSITION: 'Position: ',
    CANCELEDRESERVATION: 'Reservation Canceled.',
    DELETEDCARD: 'Card deleted.',
    CANCELATION: 'Cancel',
    CANCELLED: 'Cancelled',
    CANCELATIONCONFIRM: 'Confirm cancellation',
    CANCELATIONMESSAGE: 'Do you want to cancel this reservation?',
    CANCELLATION_WITHOUT_CREDIT_ALERT: 'The deadline for cancellation has passed. If you cancel now you will not receive your credit back.',
    RESERVATION: 'Reservation',
    PAYMENT: 'Payment types',
    AVAILABILITY: 'Available',
    FILTER_LABEL: 'Filters',
    FILTER_ALL_BRANDS: 'Brands',
    FILTER_ALL_LOCATIONS: 'Locations',
    FILTER_ALL_SERVICES: 'Services',
    FILTER_ALL_ROOMS: 'Rooms',
    PROFILE_NEXT_CLASSES: 'My upcoming _|_',
    PROFILE_PAST_CLASSES: 'History of _|_',
    PROFILE_PURCHASE_HISTORY: 'Purchase history',
    PROFILE_MY_CLASSES: 'My _|_',
    PROFILE_NO_PURCHASES: 'You have no purchases',
    PROFILE_NO_CLASS_HISTORY: 'You have no history of _|_',
    PROFILE_NO_UPCOMING_CLASSES: 'You have no upcoming _|_',
    PROFILE_NO_CREDITS_OR_MEMBERSHIPS: 'You have no credits or memberships!',
    PROFILE_NO_PAYMENT_CARDS: 'You have no payment cards',
    PROFILE_MALE_GENDER: 'Male',
    PROFILE_FEMALE_GENDER: 'Female',
    PROFILE_USER_GREETING: 'Hello _|_!',
    PROFILE_CARD_NUMBER: 'Card number',
    PROFILE_MY_CARDS: 'My cards',
    PROFILE_ADD_CARD: 'Add card',
    PASSWORD_RESET_SENT_EMAIL_ALERT: 'Password reset email sent! Check your inbox to follow the process.',
    PROFILE_POSITION: 'Position: _|_',
    PROFILETOTALS: 'Totals',
    RESERVED_CLASSES: 'Reserved Classes',
    ATTENDED_CLASSES: 'Attended Classes',
    NO_SHOW_CLASSES: 'No Show',
    CANCELLED_CLASSES: 'Cancelled Classes',
    TIME_ASSISTED: 'Attended Minutes',
    FAVORITE_STAFF: 'Favorite Instructors',
    FAVORITE_TIME: 'Favorite Times',
    SUBSTITUTE_INDICATOR: 'S:',
}