export default {
    BUTTON_ACCEPT: 'Aceptar',
    BUTTON_CANCEL: 'Cancelar',
    BUTTON_SAVE: 'Guardar',
    BUTTON_RESERVE: 'Reservar',
    BUTTON_BUY: 'Comprar',
    BUTTON_LOGIN: 'Iniciar sesión',
    BUTTON_LOGOUT: 'Cerrar sesión',
    BUTTON_REGISTER: 'Regístrate',
    BUTTON_PASSWORD_FORGOT: 'Recuperar contraseña',
    BUTTON_PASSWORD_CHANGE: 'Cambiar contraseña',
    BUTTON_PROFILE: 'Perfil de usuario',
    BUTTON_BACK: 'Regresar',
    VALIDATION_EMAIL: 'no es válido. Verifique la @ y que tenga un dominio correcto.',
    VALIDATION_PASSWORD: 'es muy corto. Use 6 o más caracteres.',
    VALIDATION_EQUAL_PASSWORDS: 'y la contraseña no coinciden.',
    VALIDATION_FULL_NAME: 'no debe estar vacío.',
    THE_FIELD: 'El campo ',
    LOGIN_SUCCESS: 'Ha iniciado sesión correctamente',
    REGISTER_SUCCESS: 'Se ha registrado correctamente',
    SAVE_ME_SUCCESS: 'Información del usuario guardada correctamente',
    PASSWORD_FORGOT_SUCCESS: 'Le hemos enviado un enlace para recuperar su contraseña',
    PASSWORD_CHANGE_SUCCESS: 'Se ha cambiado correctamente su contraseña',
    LABEL_EMAIL: 'Correo electrónico',
    LABEL_PASSWORD: 'Contraseña',
    LABEL_PASSWORD_CONFIRM: 'Confirmar contraseña',
    LABEL_FULL_NAME: 'Nombre completo',
    LABEL_FIRST_NAME: 'Nombre(s)',
    LABEL_LAST_NAME: 'Apellido(s)',
    LABEL_BIRTH_DATE: 'Fecha de nacimiento',
    LABEL_ADDRESS: 'Dirección',
    LABEL_INTERNAL_NUMBER: 'Interior',
    LABEL_EXTERNAL_NUMBER: 'Exterior',
    LABEL_MUNICIPALITY: 'Municipio',
    LABEL_CITY: 'Ciudad',
    LABEL_COUNTRY: 'País',
    LABEL_STATE: 'Estado',
    LABEL_PHONE: 'Teléfono',
    LABEL_CEL_PHONE: 'Celular',
    LABEL_GENDER: 'Género',
    LABEL_POSTAL_CODE: 'Código postal',
    LABEL_PROFILE_INFO: 'Usuario',
    LABEL_CONTACT: 'Contacto',
    TO_VALIDATION: {
        email: 'correo',
        password: 'contraseña',
        passwordConfirmation: 'confirmar contraseña',
        fullName: 'nombre completo',
        first_name: 'nombre',
    },
    EXPIRE_IN: "Expira en",
    DAYS: "días",
    MEMBERSHIPS: "Membresías",
    COMBOS: "Paquetes",
    STAFF_LIST: "Instructores",
    SERVICE_LIST: "Servicios",
    ALL: 'Todos',
    LOCATION: 'Ubicación',
    SERVICE: 'Servicio',
    ROOM: 'Salón',
    NEXT_WEEK: 'Siguiente semana',
    PREVIOUS_WEEK: 'Semana anterior',
    CALENDAR: 'Calendario',
    SERVICE_LIST: "Servicios",
    NOT_ACCOUNT_QUESTION: "¿Aún no tienes una cuenta?",
    ACCOUNT_QUESTION: "¿Ya tienes una cuenta?",
    FORGOT_PASSWORD_QUESTION: "¿Olvidaste tu contraseña?",
    TIME_OF_DAY: 'Periodo',
    MORNING: 'Mañana',
    AFTERNOON: 'Tarde',
    CHANGEPASSWORD: 'Cambiar Contraseña',
    NEWPASSWORD: 'Nueva Contraseña',
    PASSWORDCONFIRM: 'Confirmar contraseña',
    EXPIRATION: 'Expira:',
    CREDITS: 'Creditos disponibles',
    CREATE: 'Creado desde:',
    CLASS: 'Clases',
    PROFILE: 'Perfil',
    PAYMENTMETHODS: 'Formas de pago',
    CREDIT: 'Credito: ',
    MEMBERSHIP: 'Membresía: ',
    BEGINS: 'Empieza: ',
    FUTURESCLASSES: 'Clases Futuras',
    PASTCLASSES: 'Clases Pasadas',
    PURCHASES: 'Compras',
    POSITION: 'Posición: ',
    CANCELEDRESERVATION: 'Reserva Cancelada.',
    CANCELATION: 'Cancelar',
    CANCELLED: 'Cancelada',
    CANCELATIONCONFIRM: 'Confirmar Cancelación',
    CANCELATIONMESSAGE: '¿Desea cancelar esta reserva?',
    RESERVATION: 'Reserva'



}