export default {
    BUTTON_ACCEPT: 'Accept',
    BUTTON_CANCEL: 'Cancel',
    BUTTON_SAVE: 'Save',
    BUTTON_RESERVE: 'Reserve',
    BUTTON_BUY: 'Buy',
    BUTTON_LOGIN: 'Login',
    BUTTON_LOGOUT: 'Logout',
    BUTTON_REGISTER: 'Register',
    BUTTON_PASSWORD_FORGOT: 'Restore password',
    BUTTON_PASSWORD_CHANGE: 'Change password',
    BUTTON_PROFILE: 'User profile',
    BUTTON_BACK: 'Back',
    VALIDATION_EMAIL: 'is not valid. Verify your username and the domain address.',
    VALIDATION_PASSWORD: 'too short. Use 6 or more characters.',
    VALIDATION_EQUAL_PASSWORDS: 'and the password don\'t coincide.',
    VALIDATION_FULL_NAME: 'should not be empty.',
    THE_FIELD: 'The field ',
    LOGIN_SUCCESS: 'You\'ve logged in successfully',
    REGISTER_SUCCESS: 'You\'ve registered successfully',
    SAVE_ME_SUCCESS: 'User information saved correctly',
    PASSWORD_FORGOT_SUCCESS: 'We\'ve sent you a link to restore your password',
    PASSWORD_CHANGE_SUCCESS: 'The password has been changed correctly',
    LABEL_EMAIL: 'E-Mail',
    LABEL_PASSWORD: 'Password',
    LABEL_PASSWORD_CONFIRM: 'Confirm password',
    LABEL_FULL_NAME: 'Full name',
    LABEL_FIRST_NAME: 'Name(s)',
    LABEL_LAST_NAME: 'Last name(s)',
    LABEL_BIRTH_DATE: 'Brth date',
    LABEL_ADDRESS: 'Address',
    LABEL_INTERNAL_NUMBER: 'Interior',
    LABEL_EXTERNAL_NUMBER: 'Exterior',
    LABEL_MUNICIPALITY: 'Municipality',
    LABEL_CITY: 'City',
    LABEL_COUNTRY: 'Country',
    LABEL_STATE: 'State',
    LABEL_PHONE: 'Phone',
    LABEL_CEL_PHONE: 'Celphone',
    LABEL_GENDER: 'Gender',
    LABEL_POSTAL_CODE: 'ZIP code',
    LABEL_PROFILE_INFO: 'User data',
    LABEL_CONTACT: 'Contact',
    TO_VALIDATION: {
        email: 'email',
        password: 'password',
        passwordConfirmation: 'confirm password',
        fullName: 'full name',
        first_name: 'name',
    },
    EXPIRE_IN: "Expires in ",
    DAYS: "days",
    MEMBERSHIPS: "Memberships",
    COMBOS: "Combos",
    STAFF_LIST: "Staff",
    SERVICE_LIST: "Services",
    ALL: 'All',
    LOCATION: 'Location',
    SERVICE: 'Service',
    ROOM: 'Room',
    NEXT_WEEK: 'Next week',
    PREVIOUS_WEEK: 'Previous week',
    CALENDAR: 'Calendar',
    NOT_ACCOUNT_QUESTION: "Don\'t have an account yet?",
    ACCOUNT_QUESTION: "Already have an account?",
    FORGOT_PASSWORD_QUESTION: "Forgot your password?",
    TIME_OF_DAY: 'Time of day',
    MORNING: 'Morning',
    AFTERNOON: 'Afternoon',
    CHANGEPASSWORD: 'Change password',
    NEWPASSWORD: 'New password',
    PASSWORDCONFIRM: 'Confirm password',
    EXPIRATION: 'Expires:',
    CREDITS: 'Available credits',
    CREATE: 'Created since:',
    CLASS: 'My classes',
    PROFILE: 'My profile',
    PAYMENTMETHODS: 'Payment types',
    CREDIT: 'Credit: ',
    MEMBERSHIP: 'Membership: ',
    BEGINS: 'Starts: ',
    FUTURESCLASSES: 'Upcoming Classes',
    PASTCLASSES: 'Past Classes',
    PURCHASES: 'Purchases',
    POSITION: 'Position: ',
    CANCELEDRESERVATION: 'Reservation Canceled.',
    DELETEDCARD: 'Card deleted.',
    CANCELATION: 'Cancel',
    CANCELLED: 'Cancelled',
    CANCELATIONCONFIRM: 'Confirm cancellation',
    CANCELATIONMESSAGE: 'Do you want to cancel this reservation?',
    RESERVATION: 'Reservation',
    PAYMENT: 'Payment types',
    AVAILABILITY: 'Available',
}