export default {
    BUTTON_ACCEPT: 'Aceptar',
    BUTTON_CANCEL: 'Cancelar',
    BUTTON_SAVE: 'Guardar',
    BUTTON_RESERVE: 'Reservar',
    BUTTON_BUY: 'Comprar',
    BUTTON_LOGIN: 'Iniciar sesión',
    BUTTON_LOGOUT: 'Cerrar sesión',
    BUTTON_REGISTER: 'Regístrate',
    BUTTON_PASSWORD_FORGOT: 'Recuperar contraseña',
    BUTTON_PASSWORD_CHANGE: 'Cambiar contraseña',
    BUTTON_PROFILE: 'Perfil de usuario',
    BUTTON_BACK: 'Regresar',
    VALIDATION_EMAIL: 'no es válido. Verifique la @ y que tenga un dominio correcto.',
    VALIDATION_PASSWORD: 'es muy corto. Use 6 o más caracteres.',
    VALIDATION_EQUAL_PASSWORDS: 'y la contraseña no coinciden.',
    VALIDATION_FULL_NAME: 'no debe estar vacío.',
    THE_FIELD: 'El campo ',
    LOGIN_SUCCESS: 'Ha iniciado sesión correctamente',
    REGISTER_SUCCESS: 'Bienvenido. Se ha registrado correctamente.' +
        ' En breves lo redireccionaremos.',
    SAVE_ME_SUCCESS: 'Información del usuario guardada correctamente',
    PASSWORD_FORGOT_SUCCESS: 'Le hemos enviado un enlace para recuperar su contraseña',
    PASSWORD_CHANGE_SUCCESS: 'Se ha cambiado correctamente su contraseña',
    LABEL_EMAIL: 'Correo electrónico',
    LABEL_PASSWORD: 'Contraseña',
    LABEL_PASSWORD_CONFIRM: 'Confirmar contraseña',
    LABEL_FULL_NAME: 'Nombre completo',
    LABEL_FIRST_NAME: 'Nombre(s)',
    LABEL_LAST_NAME: 'Apellido(s)',
    LABEL_BIRTH_DATE: 'Fecha de nacimiento',
    LABEL_PICTURE: 'Imágen de Perfil',
    LABEL_ADDRESS: 'Dirección',
    LABEL_INTERNAL_NUMBER: 'Interior',
    LABEL_EXTERNAL_NUMBER: 'Exterior',
    LABEL_MUNICIPALITY: 'Municipio',
    LABEL_CITY: 'Ciudad',
    LABEL_COUNTRY: 'País',
    LABEL_STATE: 'Estado',
    LABEL_PHONE: 'Teléfono',
    LABEL_CEL_PHONE: 'Celular',
    LABEL_GENDER: 'Género',
    LABEL_POSTAL_CODE: 'Código postal',
    LABEL_PROFILE_INFO: 'Datos de usuario',
    LABEL_CONTACT: 'Contacto',
    TO_VALIDATION: {
        email: 'correo',
        password: 'contraseña',
        passwordConfirmation: 'confirmar contraseña',
        fullName: 'nombre completo',
        first_name: 'nombre',
    },
    EXPIRE_IN: "Expiración ",
    DAYS: "días",
    MEMBERSHIPS: "Membresías",
    COMBOS: "Paquetes",
    STAFF_LIST: "Staff",
    SERVICE_LIST: "Servicios",
    ALL: 'Todos',
    LOCATION: 'Ubicación',
    SERVICE: 'Servicio',
    ROOM: 'Salón',
    NEXT_WEEK: 'Siguiente semana',
    PREVIOUS_WEEK: 'Semana anterior',
    CALENDAR: 'Calendario',
    NOT_ACCOUNT_QUESTION: "¿Aún no tienes una cuenta?",
    ACCOUNT_QUESTION: "¿Ya tienes una cuenta?",
    FORGOT_PASSWORD_QUESTION: "¿Olvidaste tu contraseña?",
    TIME_OF_DAY: 'Período',
    MORNING: 'Mañana',
    AFTERNOON: 'Tarde',
    CHANGEPASSWORD: 'Cambiar contraseña',
    NEWPASSWORD: 'Nueva contraseña',
    PASSWORDCONFIRM: 'Confirmar contraseña',
    EXPIRATION: 'Expira:',
    CREDITS: 'Créditos disponibles',
    STORE_CREDIT_AVAILABLE: 'Crédito en tienda disponible',
    CREATE: 'Creado desde:',
    CLASS: 'Mis clases',
    PROFILE: 'Mi Perfil',
    PAYMENTMETHODS: 'Formas de pago',
    CREDIT: 'Credito: ',
    MEMBERSHIP: 'Membresía: ',
    BEGINS: 'Empieza: ',
    FUTURESCLASSES: 'Clases Futuras',
    PASTCLASSES: 'Clases Pasadas',
    PURCHASES: 'Compras',
    POSITION: 'Posición: ',
    CANCELEDRESERVATION: 'Reserva Cancelada.',
    DELETEDCARD: 'Tarjeta eliminada.',
    CANCELATION: 'Cancelar',
    CANCELLED: 'Cancelada',
    CANCELEDWAITLIST: 'Waitlist Cancelada',
    CANCELATIONCONFIRM: 'Sí, deseo cancelar',
    CANCELATIONMESSAGE: '¿Desea cancelar esta reserva?',
    CANCELATIONMESSAGEWAITLIST: '¿Le gustaría cancelar su lugar en la lista de espera?',
    CANCELLATION_WITHOUT_CREDIT_ALERT: 'Ya ha pasado la hora límite para cancelar. Si cancelas ahora no recibirás tu crédito de vuelta.',
    RESERVATION: 'Reserva',
    PAYMENT: 'Formas de pago',
    AVAILABILITY: 'Disponible',
    FILTER_LABEL: 'Filtros',
    FILTER_ALL_BRANDS: 'Marcas',
    FILTER_ALL_LOCATIONS: 'Ubicaciones',
    FILTER_ALL_SERVICES: 'Servicios',
    FILTER_ALL_ROOMS: 'Salones',
    PROFILE_NEXT_CLASSES: 'Mis próximas _|_',
    PROFILE_PAST_CLASSES: 'Historial de _|_',
    PROFILE_PURCHASE_HISTORY: 'Historial de compras',
    PROFILE_MY_CLASSES: 'Mis _|_',
    PROFILE_NO_PURCHASES: 'No cuentas con compras',
    PROFILE_NO_CLASS_HISTORY: 'No cuentas con historial de _|_',
    PROFILE_NO_UPCOMING_CLASSES: 'No cuentas con próximas _|_',
    PROFILE_NO_CREDITS_OR_MEMBERSHIPS: '¡No cuentas con créditos ni membresías!',
    PROFILE_NO_PAYMENT_CARDS: 'No cuentas con tarjetas para pagos',
    PROFILE_MALE_GENDER: 'Hombre',
    PROFILE_FEMALE_GENDER: 'Mujer',
    PROFILE_USER_GREETING: '¡Hola _|_!',
    PROFILE_WELCOME: 'Bienvenid@',
    PROFILE_CARD_NUMBER: 'Número de tarjeta',
    PROFILE_MY_CARDS: 'Mis tarjetas',
    PROFILE_ADD_CARD: 'Añadir tarjeta',
    PASSWORD_RESET_SENT_EMAIL_ALERT: '¡Correo de cambio de contraseña enviado! Revisa tu bandeja de correo electrónico para continuar el proceso.',
    PROFILE_POSITION: 'Posición: _|_',
    PROFILETOTALS: 'Mi Actividad',
    RESERVED_CLASSES: 'Clases Reservadas',
    ATTENDED_CLASSES: 'Clases Asistidas',
    NO_SHOW_CLASSES: 'No Show',
    CANCELLED_CLASSES: 'Clases Canceladas',
    TIME_ASSISTED: 'Minutos Asistidos',
    FAVORITE_STAFF: 'Instructores Favoritos',
    FAVORITE_TIME: 'Horarios Favoritos',
    SUBSTITUTE_INDICATOR: 'S:',
    PROFILE_RESERVATIONS_FORMAT: 'dd DD [de] MMM',
    PROFILE_RESERVATIONS_NO_DATE: 'Sin fecha',
    PROFILE_RESERVATIONS_NO_TIME: 'Sin horario',
    PROFILE_RESERVATIONS_NO_STAFF: 'Sin nombre de staff',
    PROFILE_RESERVATIONS_NO_SERVICE: 'Sin servicio',
    PROFILE_RESERVATIONS_NO_LOCATION: 'Sin ubicación',
    CALENDAR_ALREADY_RESERVED: 'Ya tienes una o más reservas en esta clase'
}