export default {
    BUTTON_ACCEPT: 'Aceptar',
    BUTTON_CANCEL: 'Cancelar',
    BUTTON_SAVE: 'Guardar',
    BUTTON_RESERVE: 'Reservar',
    BUTTON_BUY: 'Comprar',
    BUTTON_LOGIN: 'Iniciar sesión',
    BUTTON_REGISTER: 'Regístrate',
    VALIDATION_EMAIL: 'no es válido. Verifique la @ y que tenga un dominio correcto.',
    VALIDATION_PASSWORD: 'es muy corto. Use 6 o más caracteres.',
    VALIDATION_EQUAL_PASSWORDS: 'y la contraseña no coinciden.',
    VALIDATION_FULL_NAME: 'no debe estar vacío.',
    THE_FIELD: 'El campo ',
    LOGIN_SUCCESS: 'Ha iniciado sesión correctamente',
    REGISTER_SUCCESS: 'Se ha registrado correctamente',
    LABEL_EMAIL: 'Correo electrónico',
    LABEL_PASSWORD: 'Contraseña',
    LABEL_PASSWORD_CONFIRM: 'Confirmar contraseña',
    LABEL_FULL_NAME: 'Nombre completo',
    TO_VALIDATION:{
        email: 'correo',
        password: 'contraseña',
        passwordConfirmation: 'confirmar contraseña',
        fullName: 'nombre completo',
    },
    EXPIRE_IN: "Expira en",
    DAYS: "días",
    MEMBERSHIPS: "Membresías",
    COMBOS: "Paquetes",
    STAFF_LIST: "Instructores",
    SERVICE_LIST: "Servicios"
}