import type { BuqNextCatalogoSede } from "./buqNextContract";

/**
 * Next Studio — la sede nativa de prueba que cita el plan (`next-studio-e0f9`).
 * Precios en centavos. Clases con offset relativo a hoy para que el calendario
 * del preview nunca quede vacío.
 */
export const NEXT_STUDIO_FIXTURES: BuqNextCatalogoSede = {
  organizacion: {
    id: "org-next-studio-0001",
    numericId: 9001,
    nombre: "Next Studio",
    slug: "next-studio",
  },
  marca: {
    id: "brand-next-studio-0001",
    numericId: 9101,
    nombre: "Next Studio",
    slug: "next-studio",
    zonaHoraria: "America/Mexico_City",
    moneda: "MXN",
  },
  sede: {
    id: "next-studio-e0f9",
    numericId: 9201,
    nombre: "Next Studio CDMX",
    slug: "next-studio-cdmx",
    marcaId: "brand-next-studio-0001",
    diasCalendario: 14,
  },
  servicios: [
    {
      id: "svc-reformer-0001",
      numericId: 9301,
      nombre: "Reformer",
      descripcion: "Pilates reformer en grupo.",
      duracionMinutos: 50,
    },
    {
      id: "svc-strength-0001",
      numericId: 9302,
      nombre: "Strength",
      descripcion: "Fuerza y acondicionamiento.",
      duracionMinutos: 45,
    },
    {
      id: "svc-yoga-0001",
      numericId: 9303,
      nombre: "Yoga Flow",
      descripcion: "Flujo suave de 45 minutos.",
      duracionMinutos: 45,
    },
  ],
  coaches: [
    {
      id: "coach-maria-0001",
      numericId: 9401,
      nombre: "María",
      apellido: "Solís",
      apodo: "Mari",
      bio: "Coach principal de reformer.",
    },
    {
      id: "coach-diego-0001",
      numericId: 9402,
      nombre: "Diego",
      apellido: "Ramos",
      bio: "Fuerza y movilidad.",
    },
    {
      id: "coach-ana-0001",
      numericId: 9403,
      nombre: "Ana",
      apellido: "Vega",
      apodo: "Ani",
      bio: "Yoga y movilidad.",
    },
  ],
  salones: [
    {
      id: "salon-reforma-0001",
      numericId: 9501,
      nombre: "Salón Reforma",
      capacidad: 12,
      tieneMapa: true,
    },
    {
      id: "salon-terraza-0001",
      numericId: 9502,
      nombre: "Salón Terraza",
      capacidad: 8,
      tieneMapa: false,
    },
  ],
  clases: [
    {
      id: "clase-reformer-am-0001",
      numericId: 9601,
      sedeId: "next-studio-e0f9",
      servicioId: "svc-reformer-0001",
      coachId: "coach-maria-0001",
      salonId: "salon-reforma-0001",
      diasDesdeHoy: 0,
      hora: "07:00",
      zonaHoraria: "America/Mexico_City",
      cupo: 12,
      reservados: 4,
      listaEspera: true,
      nota: "Llega 10 minutos antes. Trae calcetas antideslizantes.",
    },
    {
      id: "clase-strength-am-0001",
      numericId: 9602,
      sedeId: "next-studio-e0f9",
      servicioId: "svc-strength-0001",
      coachId: "coach-diego-0001",
      salonId: "salon-terraza-0001",
      diasDesdeHoy: 0,
      hora: "18:30",
      zonaHoraria: "America/Mexico_City",
      cupo: 8,
      reservados: 8,
      listaEspera: true,
    },
    {
      id: "clase-yoga-pm-0001",
      numericId: 9603,
      sedeId: "next-studio-e0f9",
      servicioId: "svc-yoga-0001",
      coachId: "coach-ana-0001",
      salonId: "salon-terraza-0001",
      diasDesdeHoy: 1,
      hora: "09:00",
      zonaHoraria: "America/Mexico_City",
      cupo: 8,
      reservados: 2,
      listaEspera: false,
    },
    {
      id: "clase-reformer-pm-0001",
      numericId: 9604,
      sedeId: "next-studio-e0f9",
      servicioId: "svc-reformer-0001",
      coachId: "coach-maria-0001",
      salonId: "salon-reforma-0001",
      diasDesdeHoy: 2,
      hora: "19:00",
      zonaHoraria: "America/Mexico_City",
      cupo: 12,
      reservados: 11,
      listaEspera: true,
    },
    {
      id: "clase-strength-sat-0001",
      numericId: 9605,
      sedeId: "next-studio-e0f9",
      servicioId: "svc-strength-0001",
      coachId: "coach-diego-0001",
      salonId: "salon-terraza-0001",
      diasDesdeHoy: 3,
      hora: "10:00",
      zonaHoraria: "America/Mexico_City",
      cupo: 8,
      reservados: 1,
      listaEspera: false,
    },
  ],
  ofertas: [
    {
      id: "oferta-paquete-5-0001",
      numericId: 9701,
      tipo: "paquete",
      nombre: "5 clases",
      descripcion: "Paquete de arranque. Válido 45 días.",
      precioCentavos: 165000,
      moneda: "MXN",
      creditos: 5,
      vigenciaDias: 45,
    },
    {
      id: "oferta-paquete-10-0001",
      numericId: 9702,
      tipo: "paquete",
      nombre: "10 clases",
      descripcion: "El más usado en Next Studio.",
      precioCentavos: 290000,
      moneda: "MXN",
      creditos: 10,
      vigenciaDias: 90,
    },
    {
      id: "oferta-membresia-mensual-0001",
      numericId: 9703,
      tipo: "membresia",
      nombre: "Ilimitada mensual",
      descripcion: "Clases ilimitadas por 30 días.",
      precioCentavos: 249900,
      moneda: "MXN",
      vigenciaDias: 30,
      suscribible: true,
    },
    {
      id: "oferta-producto-agua-0001",
      numericId: 9704,
      tipo: "producto",
      nombre: "Agua",
      descripcion: "Botella 600 ml.",
      precioCentavos: 4000,
      moneda: "MXN",
    },
    {
      id: "oferta-producto-toalla-0001",
      numericId: 9705,
      tipo: "producto",
      nombre: "Toalla",
      descripcion: "Toalla de estudio.",
      precioCentavos: 28000,
      moneda: "MXN",
    },
  ],
};
